// apps/desktop/src/app/components/actions-panel.tsx
import {
  Calculator,
  Calendar,
  CreditCard,
  Settings,
  Smile,
  User,
} from 'lucide-react'
import * as React from 'react'
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
  CommandShortcut,
} from '@/components/ui/command'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'

import { Hotkeys } from '../../components/ui/hotkeys'
import { CommandFooterButton } from './command-footer'

function ActionsPanel() {
  return (
    <Popover modal>
      <PopoverTrigger asChild>
        <CommandFooterButton>
          Actions
          <Hotkeys keys="Ctrl+k" />
        </CommandFooterButton>
      </PopoverTrigger>
      <PopoverContent side="top" align="end" sideOffset={16} alignOffset={0}>
        <Command className="rounded-lg border shadow-md w-80 h-64">
          <CommandList>
            <CommandEmpty>No results found.</CommandEmpty>
            <CommandGroup heading="Suggestions">
              <CommandItem>
                <Calendar />
                <span>Calendar</span>
              </CommandItem>
              <CommandItem>
                <Smile />
                <span>Search Emoji</span>
              </CommandItem>
              <CommandItem disabled>
                <Calculator />
                <span>Calculator</span>
              </CommandItem>
            </CommandGroup>
            <CommandSeparator />
            <CommandGroup heading="Settings">
              <CommandItem>
                <User />
                <span>Profile</span>
                <CommandShortcut>⌘P</CommandShortcut>
              </CommandItem>
              <CommandItem>
                <CreditCard />
                <span>Billing</span>
                <CommandShortcut>⌘B</CommandShortcut>
              </CommandItem>
              <CommandItem>
                <Settings />
                <span>Settings</span>
                <CommandShortcut>⌘S</CommandShortcut>
              </CommandItem>
            </CommandGroup>
          </CommandList>
          <CommandInput placeholder="Type a command or search..." />
        </Command>
      </PopoverContent>
    </Popover>
  )
}

export { ActionsPanel }

// apps/desktop/src/lib/components/layout/ActionsPanel.svelte
<script lang='ts' module>
  import type { Snippet } from 'svelte'

  export interface Action {
    title: string
    icon?: string
    shortcut?: string
  }

  export interface Section {
    heading?: string
    actions: Action[]
  }

  export interface ActionsProps {
    child?: Snippet<[{ props: Record<string, unknown> }]>
    children?: Snippet
    align?: 'start' | 'center' | 'end'
    sections: Section[]
  }
</script>

<script lang='ts'>
  import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator, CommandViewport } from '$lib/components/ui/command'
  import { Popover, PopoverContent, PopoverTrigger } from '$lib/components/ui/popover'
  import { ScrollArea } from '$lib/components/ui/scroll-area'

  const { align = 'end', sections, ...restProps }: ActionsProps = $props()
</script>

<Popover>
  <PopoverTrigger {...restProps} />
  <PopoverContent {align} sideOffset={12} class='p-0 w-96 h-60 bg-actionsPanel-background electron-smooth'>
    <Command>
      <ScrollArea type='scroll' class='h-0 flex-1' scrollHideDelay={1800}>
        <CommandList>
          <CommandViewport>
            <CommandEmpty>No results found.</CommandEmpty>
            {#each sections as section, i}
              <CommandGroup class='p-2' heading={section.heading}>
                {#each section.actions as action}
                  <CommandItem class='h-9 p-2'>{action.title}</CommandItem>
                {/each}
              </CommandGroup>
              {#if i < sections.length - 1}
                <CommandSeparator class='bg-border' />
              {/if}
            {/each}
          </CommandViewport>
        </CommandList>
      </ScrollArea>
      <div class='h-10 px-4 box-content border-t flex items-center'>
        <CommandInput placeholder='Search...' />
      </div>
    </Command>
  </PopoverContent>
</Popover>
