// apps/desktop/src/app/components/Footer.tsx
'use client'

import { cn } from '@/lib/utils'

// React.HTMLAttributes<HTMLDivElement>
export function Footer({ className }: React.ComponentPropsWithoutRef<'div'>) {
  return (
    <div className={cn('h-10 border-t px-3 flex justify-between', className)}>
      <div></div>
      <div></div>
    </div>
  )
}

// apps/desktop/src/lib/components/layout/Footer.svelte
<script lang='ts'>
  import type { HTMLAttributes } from 'svelte/elements'
  import { cn } from '$lib/utils'

  type CommandFooterProps = HTMLAttributes<HTMLElement> & {}

  const { class: className, ...restProps }: CommandFooterProps = $props()
</script>

<footer data-slot='layout-footer' class={cn('h-10 px-3 flex border-t justify-between', className)} {...restProps}>
  <div></div>
  <div></div>
</footer>
